* Todos
** TODO  Figuring namespacing/style for functions and variables
** DONE Make this into a proper Emacs module for MELPA
CLOSED: [2015-07-19 Sun 13:03]
** TODO  Persistent Action should show info as in the webpage      :feature:
Create an action that prints the data in a nicely formated way in a temporary buffer
** DONE Create a company-mode backend for this for nix-mode?
CLOSED: [2015-07-19 Sun 13:01]
** TODO  Feature: Hyperlink Options file 
"Declared In" has link to the file where this option is. Query the system to
find out where in the store this is. Make a hyperlink to this file.
** TODO  Use also nixos-packages-json-file for helm completions      <2015-07-20 Mon 00:47>

In that way one can check for packages as well
 
 Link: file:~/spacemacs_conf/nix/extensions/nix-options/nixos-options.el::(defvar%20nixos-options-json-file
** TODO Figure out nixos options Data Structure for Company

#+begin_src emacs-lisp
  ("xserver" .
   (("window-manager" . (("description" . meta) ("subcategories" . ("i3" . ( ("description" .  description) )))))
   ("enable" (("description" . description)))))
#+end_src



